name: Publish docs

on:
    push:
        branches:
            - master
            - dev

jobs:
    build-docs:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: JetBrains/writerside-github-action@v4
              with:
                  instance: 'docs/theatrum'
                  artifact: 'webHelpTHEATRUM2-all.zip'
                  docker-version: '243.21565'
            - run: mv artifacts en
            - uses: JetBrains/writerside-github-action@v4
              with:
                  instance: 'docs/theatrum_ru'
                  artifact: 'webHelpTHEATRUM_RU2-all.zip'
                  docker-version: '243.21565'
            - run: mv artifacts ru
            - run: mkdir content
            - run: unzip -O UTF-8 -qq -d ./content ./en/webHelpTHEATRUM2-all.zip
            - run: unzip -O UTF-8 -qq -d ./content/ru ./ru/webHelpTHEATRUM_RU2-all.zip
            - uses: actions/configure-pages@v4
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: content
            - id: deployment
              uses: actions/deploy-pages@v4
