name: Publish

on:
    push:
        branches:
            - master
            - dev

jobs:
    publish-core:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.11.x
            - run: cd packages/core && deno task dnt
            - run: deno task publish:core
    publish-console:
        needs: publish-core
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.11.x
            - run: cd packages/console
            - run: deno task publish:console
