name: Publish

on:
    push:
        branches:
            - master
            - dev

jobs:
    publish-jsr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - run: deno task publish:core
            - run: deno task publish:console
