name: Publish

on:
    push:
        branches:
            - master
            - dev

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - run: (curl -fsSL https://deno.land/install.sh | sh) && deno task publish-core
