name: Publish

on:
    push:
        branches:
            - master

jobs:
    publish-core:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.11.x
            - run: cd packages/core && deno task dnt
            - run: deno task publish:core
    publish-console:
        needs: publish-core
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.11.x
            - run: |
                  cd packages/console/web
                  yarn install --frozen-lockfile
                  rm -rf node_modules
                  cd ../
                  deno task build
                  deno task bundle
            - run: deno task publish:console
    publish-docs:
        needs:
            - publish-core
            - publish-console
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: JetBrains/writerside-github-action@v4
              with:
                  instance: 'docs/theatrum'
                  artifact: 'webHelpTHEATRUM2-all.zip'
                  docker-version: '243.21565'
            - run: mv artifacts en
            - uses: JetBrains/writerside-github-action@v4
              with:
                  instance: 'docs/theatrum_ru'
                  artifact: 'webHelpTHEATRUM_RU2-all.zip'
                  docker-version: '243.21565'
            - run: mv artifacts ru
            - run: mkdir content
            - run: unzip -O UTF-8 -qq -d ./content ./en/webHelpTHEATRUM2-all.zip
            - run: unzip -O UTF-8 -qq -d ./content/ru ./ru/webHelpTHEATRUM_RU2-all.zip
            - uses: actions/configure-pages@v4
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: content
            - id: deployment
              uses: actions/deploy-pages@v4
